# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thinking in Models
email: richard@qyoom.com
description: > # this means to ignore newlines until "baseurl:"
  Thinking is Models is an exploration of learning in code, dynamic visualization, 
  writing, and social media. Its inspiration draws from Scott E. Page's course
  Model Thinking on Coursera, Enrico Coen's book, Cells to Civilizations, and my
  growing interest in agent based models where group behavior emerges in complex systems.
#baseurl:  # the subpath of your site, e.g. /blog
#url:  # the base hostname & protocol for your site
twitter_username: richardlwalker
github_username:  Qyoom

# Build settings
markdown: kramdown
